# infrastructure/nginx/api.conf

server {
    listen 80;
    server_name _; # Altere para o seu domínio em produção

    # Logs de Acesso e Erro formatados para Observabilidade
    access_log /var/log/nginx/api_access.log;
    error_log /var/log/nginx/api_error.log;

    location / {
        proxy_pass http://localhost:3000; # Encaminha para o container Node
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        
        # Propaga o IP Real do Usuário (Importante para o Rate Limit!)
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Timeout de Segurança
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # Endpoint de Métricas (Protegido por IP ou Auth se necessário)
    location /metrics {
        proxy_pass http://localhost:3000/api/v1/metrics;
        # allow 127.0.0.1; # Exemplo: permitir apenas localhost (Prometheus)
        # deny all;
    }
}
